# Generated by Django 4.2.2 on 2023-06-19 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_hashtag_product_hashtag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='hashtag',
            new_name='hashtags',
        ),
    ]